name: ubuntu-clock-app
version: "3.8.480"
summary: Ubuntu Clock app
description: The clock app for all Ubuntu devices
confinement: devmode

apps:
  ubuntu-clock-app:
    command: clock
    plugs: [unity7, opengl, network, network-bind, mir]

parts:
  clock:
    source: lp:ubuntu-clock-app
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-packages:
      - build-essential
      - cmake
      - gettext
      - intltool
      - ubuntu-touch-sounds
      - suru-icon-theme
      - qml-module-qttest
      - qml-module-qtsysteminfo
      - qml-module-qt-labs-settings
      - qtdeclarative5-u1db1.0
      - qtdeclarative5-qtmultimedia-plugin
      - qtdeclarative5-qtpositioning-plugin
      - qtdeclarative5-ubuntu-content1
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtdeclarative5-folderlistmodel-plugin
      - qtdeclarative5-ubuntu-ui-toolkit-plugin
    stage-packages:
      - ubuntu-sdk-libs
      - qtubuntu-desktop
      - qtmir-desktop
      - mir-graphics-drivers-desktop
      - qtdeclarative5-dev
      - qtdeclarative5-examples
      - qmlscene
      - qtdeclarative5-qtmir-plugin
      - ttf-ubuntu-font-family
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qt-labs-settings
      - qml-module-qt-websockets
      - qml-module-qtfeedback
      - qml-module-qtgraphicaleffects
      - qml-module-qtlocation
      - qml-module-qtmultimedia
      - qml-module-qtorganizer
      - qml-module-qtpositioning
      - qml-module-qtqml-models2
      - qml-module-qtqml-statemachine
      - qml-module-qtquick-controls
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-layouts
      - qml-module-qtquick-localstorage
      - qml-module-qtquick-particles2
      - qml-module-qtquick-privatewidgets
      - qml-module-qtquick-window2
      - qml-module-qtquick-xmllistmodel
      - qml-module-qtquick2
      - qml-module-qtsensors
      - qml-module-qtsysteminfo
      - qml-module-qttest
      - qml-module-qtwebkit
      - intltool
    snap:
      - -usr/share/doc
      - -usr/include
  environment:
    plugin: copy
    files:
      clock.wrapper: bin/clock
      snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf
